### PR TITLE
pip check support in PipPackage module

### PR DESCRIPTION
**Pull request by romainx**
Hello,

This PR adds [`pip check`](https://pip.pypa.io/en/stable/reference/pip_check/) support in `PipPackage` module.

> Verify installed packages have compatible dependencies.

Best

### CODE REVIEW

**Comment by romainx** [comment]
The error is `test_ssh_service` on py36 / alpine, seems not related to this PR.

**Comment by philpep** [comment]
Merged, thanks!

**Comment by romainx** [comment]
Thank you @philpep I would like to ask you a question. 
Imagine we would like to implement something more related to the `pip` package manager than the packages themselves (for example related to `pip` configuration). Do you think it should be implemented in the `PipPackage` `class` or do you think it should be implemented in another `class` (for example called `Pip`) and dedicated to the package manager itself?

**Comment by romainx** [comment]
@philpep thanks for the quick answer. Your suggestion makes sense. I share the same opinion and I think performing this change would make the things clearer. If you're OK, I will have a deepest look at it and propose something that remains compliant with the current implementation. I will manage it in a new issue + PR. Thanks a lot for this exchange, really appreciate.

**Pull request merged**
