### PR TITLE
ansible: Support environment variables

### PR DESCRIPTION
**Pull request by BenoitKnecht**
Ansible options can now consistently be specified in the `ansible.cfg`
configuration file, in group or host variables or in environment variables, the
latter taking precedence on the former.

| Configuration File                        | Host Variable         | Environment           |
| ----------------------------------------- | --------------------- | --------------------- |
| `[privilege_escalation]`<br>`become`      | `ansible_become`      | `ANSIBLE_BECOME`      |
| `[privilege_escalation]`<br>`become_user` | `ansible_become_user` | `ANSIBLE_BECOME_USER` |
| `[defaults]`<br>`remote_port`             | `ansible_port`        | `ANSIBLE_REMOTE_PORT` |
| `[defaults]`<br>`remote_user`             | `ansible_user`        | `ANSIBLE_REMOTE_USER` |

Signed-off-by: Benoît Knecht <bknecht@protonmail.ch>

### CODE REVIEW

**Comment by philpep** [comment]
Merged, thanks!

**Comment by BenoitKnecht** [comment]
I'm really looking forward to this getting released, as it would greatly simplify running testinfra in CI jobs, where the user name needs to be read from an environment variable.

@philpep Are you planning on cutting a new release soon?

**Comment by philpep** [comment]
@BenoitKnecht sure, released in v6.5.0 and available now on pypi.

**Comment by BenoitKnecht** [comment]
@philpep That's awesome, thank you so much!

**Pull request merged**
