### PR TITLE
Rework github workflow

### PR DESCRIPTION
**Pull request by philpep**

### CODE REVIEW

**Comment by philpep** [comment]
@ssbarnea I don't understand why github action doesn't run "lint-mypy" jobs, it always hang on "tox -e lint,mypy". I tried several variations without success... Maybe you understand this or you known how to debug ? Thanks!

**Comment by ssbarnea** [comment]
I will look tomorrow, the setup is bit weird because I always consider mypy a linter, w/o a separated job.

**Comment by ssbarnea** [comment]
@philpep Ok to takeover your PR?

**Comment by philpep** [comment]
ssbarnea sure, my main concern was just about running test suite once for speed and energy saving. But also running flake8 and mypy on all supported python versions.

**Pull request closed without merging**
